# Generated by Django 5.1.1 on 2024-09-30 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="room",
            new_name="ChattingRoom",
        ),
    ]
